/* eslint-env mocha */

const assert = require('assert')
const bcrypt = require('./')

describe('Basic functionality', () => {
  it('hash', () => {
    const hash = bcrypt.hashSync('test', 8)

    assert.strictEqual(bcrypt.compareSync('wrong', hash), false)
    assert.strictEqual(bcrypt.compareSync('test', hash), true)
  })

  it('salt', () => {
    const salt1 = bcrypt.genSaltSync(8)
    const salt2 = bcrypt.genSaltSync(8)

    assert.notStrictEqual(salt1, salt2)

    assert.ok(bcrypt.genSaltSync(6).startsWith('$2b$06$'))
    assert.ok(bcrypt.genSaltSync(7).startsWith('$2b$07$'))
    assert.ok(bcrypt.genSaltSync(8).startsWith('$2b$08$'))
    assert.ok(bcrypt.genSaltSync(9).startsWith('$2b$09$'))
    assert.ok(bcrypt.genSaltSync(10).startsWith('$2b$10$'))
  })

  it('throws', () => {
    assert.throws(() => bcrypt.compareSync(), TypeError)
    assert.throws(() => bcrypt.compareSync(''), TypeError)
    assert.throws(() => bcrypt.compareSync('', 0), TypeError)
    assert.throws(() => bcrypt.compareSync(0, ''), TypeError)
    assert.throws(() => bcrypt.genSaltSync(), TypeError)
    assert.throws(() => bcrypt.genSaltSync(''), TypeError)
    assert.throws(() => bcrypt.hashSync(), TypeError)
    assert.throws(() => bcrypt.hashSync(''), TypeError)
    assert.throws(() => bcrypt.hashSync('', ''), TypeError)
    assert.throws(() => bcrypt.hashSync(0, 0), TypeError)
  })
})

describe('Test vectors', () => {
  it('StackOverflow', () => {
    // see: https://stackoverflow.com/a/12761326/774398
    assert.ok(bcrypt.compareSync('ππππππππ', '$2a$10$.TtQJ4Jr6isd4Hp.mVfZeuh6Gws4rOQ/vdBczhDx.19NFK0Y84Dle'))
    assert.ok(bcrypt.compareSync('correctbatteryhorsestapler', '$2a$12$mACnM5lzNigHMaf7O1py1O3vlf6.BA8k8x3IoJ.Tq3IB/2e7g61Km'))
  })

  it('Openwall Wiki', () => {
    // see: http://openwall.info/wiki/john/sample-hashes
    assert.ok(bcrypt.compareSync('password', '$2a$05$bvIG6Nmid91Mu9RcmmWZfO5HJIMCT8riNW0hEp8f6/FuA2/mHZFpe'))
  })

  it('Openwall CVS', () => {
    // see: http://cvsweb.openwall.com/cgi/cvsweb.cgi/Owl/packages/glibc/crypt_blowfish/wrapper.c?rev=HEAD
    assert.ok(bcrypt.compareSync('U*U', '$2a$05$CCCCCCCCCCCCCCCCCCCCC.E5YPO9kmyuRGyh0XouQYb4YMJKvyOeW'))
    assert.ok(bcrypt.compareSync('U*U*', '$2a$05$CCCCCCCCCCCCCCCCCCCCC.VGOzA784oUp/Z0DY336zx7pLYAy0lwK'))
    assert.ok(bcrypt.compareSync('U*U*U', '$2a$05$XXXXXXXXXXXXXXXXXXXXXOAcXxm9kjPGEMsLznoKqmqw7tc8WCx4a'))
    assert.ok(bcrypt.compareSync('', '$2a$06$DCq7YPn5Rq63x1Lad4cll.TV4S6ytwfsfvkgY8jIucDrjc8deX1s.'))
  })

  it('bcrypt.net', () => {
    // see: https://bitbucket.org/vadim/bcrypt.net/src/464c41416dc9/BCrypt.Net.Test/TestBCrypt.cs?fileviewer=file-view-default
    assert.ok(bcrypt.compareSync('', '$2a$08$HqWuK6/Ng6sg9gQzbLrgb.Tl.ZHfXLhvt/SgVyWhQqgqcZ7ZuUtye'))
    assert.ok(bcrypt.compareSync('', '$2a$10$k1wbIrmNyFAPwPVPSVa/zecw2BCEnBwVS2GbrmgzxFUOqW9dk4TCW'))
    assert.ok(bcrypt.compareSync('', '$2a$12$k42ZFHFWqBp3vWli.nIn8uYyIkbvYRvodzbfbK18SSsY.CsIQPlxO'))
    assert.ok(bcrypt.compareSync('a', '$2a$06$m0CrhHm10qJ3lXRY.5zDGO3rS2KdeeWLuGmsfGlMfOxih58VYVfxe'))
    assert.ok(bcrypt.compareSync('a', '$2a$08$cfcvVd2aQ8CMvoMpP2EBfeodLEkkFJ9umNEfPD18.hUF62qqlC/V.'))
    assert.ok(bcrypt.compareSync('a', '$2a$10$k87L/MF28Q673VKh8/cPi.SUl7MU/rWuSiIDDFayrKk/1tBsSQu4u'))
    assert.ok(bcrypt.compareSync('a', '$2a$12$8NJH3LsPrANStV6XtBakCez0cKHXVxmvxIlcz785vxAIZrihHZpeS'))
    assert.ok(bcrypt.compareSync('abc', '$2a$06$If6bvum7DFjUnE9p2uDeDu0YHzrHM6tf.iqN8.yx.jNN1ILEf7h0i'))
    assert.ok(bcrypt.compareSync('abc', '$2a$08$Ro0CUfOqk6cXEKf3dyaM7OhSCvnwM9s4wIX9JeLapehKK5YdLxKcm'))
    assert.ok(bcrypt.compareSync('abc', '$2a$10$WvvTPHKwdBJ3uk0Z37EMR.hLA2W6N9AEBhEgrAOljy2Ae5MtaSIUi'))
    assert.ok(bcrypt.compareSync('abc', '$2a$12$EXRkfkdmXn2gzds2SSitu.MW9.gAVqa9eLS1//RYtYCmB1eLHg.9q'))
    assert.ok(bcrypt.compareSync('abcdefghijklmnopqrstuvwxyz', '$2a$06$.rCVZVOThsIa97pEDOxvGuRRgzG64bvtJ0938xuqzv18d3ZpQhstC'))
    assert.ok(bcrypt.compareSync('abcdefghijklmnopqrstuvwxyz', '$2a$08$aTsUwsyowQuzRrDqFflhgekJ8d9/7Z3GV3UcgvzQW3J5zMyrTvlz.'))
    assert.ok(bcrypt.compareSync('abcdefghijklmnopqrstuvwxyz', '$2a$10$fVH8e28OQRj9tqiDXs1e1uxpsjN0c7II7YPKXua2NAKYvM6iQk7dq'))
    assert.ok(bcrypt.compareSync('abcdefghijklmnopqrstuvwxyz', '$2a$12$D4G5f18o7aMMfwasBL7GpuQWuP3pkrZrOAnqP.bmezbMng.QwJ/pG'))
    assert.ok(bcrypt.compareSync('~!@#$%^&*()      ~!@#$%^&*()PNBFRD', '$2a$06$fPIsBO8qRqkjj273rfaOI.HtSV9jLDpTbZn782DC6/t7qT67P6FfO'))
    assert.ok(bcrypt.compareSync('~!@#$%^&*()      ~!@#$%^&*()PNBFRD', '$2a$08$Eq2r4G/76Wv39MzSX262huzPz612MZiYHVUJe/OcOql2jo4.9UxTW'))
    assert.ok(bcrypt.compareSync('~!@#$%^&*()      ~!@#$%^&*()PNBFRD', '$2a$10$LgfYWkbzEvQ4JakH7rOvHe0y8pHKF9OaFgwUZ2q7W2FFZmZzJYlfS'))
    assert.ok(bcrypt.compareSync('~!@#$%^&*()      ~!@#$%^&*()PNBFRD', '$2a$12$WApznUOJfkEGSmYRfnkrPOr466oFDCaj4b6HY3EXGvfxm43seyhgC'))
  })

  it('FavreBcryptReferenceTests', () => {
    // see: https://github.com/patrickfav/bcrypt/blob/f387266a305937f2d0450e2e57c7f5d2843a4863/modules/bcrypt/src/test/java/at/favre/lib/crypto/bcrypt/FavreBcryptReferenceTests.java
    assert.ok(bcrypt.compareSync('', '$2a$04$zVHmKQtGGQob.b/Nc7l9NO8UlrYcW05FiuCj/SxsFO/ZtiN9.mNzy'))
    assert.ok(bcrypt.compareSync('', '$2a$05$zVHmKQtGGQob.b/Nc7l9NOWES.1hkVBgy5IWImh9DOjKNU8atY4Iy'))
    assert.ok(bcrypt.compareSync('', '$2a$06$zVHmKQtGGQob.b/Nc7l9NOjOl7l4oz3WSh5fJ6414Uw8IXRAUoiaO'))
    assert.ok(bcrypt.compareSync('', '$2a$07$zVHmKQtGGQob.b/Nc7l9NOBsj1dQpBA1HYNGpIETIByoNX9jc.hOi'))
    assert.ok(bcrypt.compareSync('', '$2a$08$zVHmKQtGGQob.b/Nc7l9NOiLTUh/9MDpX86/DLyEzyiFjqjBFePgO'))
    assert.ok(bcrypt.compareSync("<.S.2K(Zq'", '$2a$04$VYAclAMpaXY/oqAo9yUpkuWmoYywaPzyhu56HxXpVltnBIfmO9tgu'))
    assert.ok(bcrypt.compareSync('5.rApO%5jA', '$2a$05$kVNDrnYKvbNr5AIcxNzeIuRcyIF5cZk6UrwHGxENbxP5dVv.WQM/G'))
    assert.ok(bcrypt.compareSync('oW++kSrQW^', '$2a$06$QLKkRMH9Am6irtPeSKN5sObJGr3j47cO6Pdf5JZ0AsJXuze0IbsNm'))
    assert.ok(bcrypt.compareSync('ggJ\\KbTnDG', '$2a$07$4H896R09bzjhapgCPS/LYuMzAQluVgR5iu/ALF8L8Aln6lzzYXwbq'))
    assert.ok(bcrypt.compareSync('49b0:;VkH/', '$2a$08$hfvO2retKrSrx5f2RXikWeFWdtSesPlbj08t/uXxCeZoHRWDz/xFe'))
    assert.ok(bcrypt.compareSync(">9N^5jc##'", '$2a$09$XZLvl7rMB3EvM0c1.JHivuIDPJWeNJPTVrpjZIEVRYYB/mF6cYgJK'))
    assert.ok(bcrypt.compareSync('\\$ch)s4WXp', '$2a$10$aIjpMOLK5qiS9zjhcHR5TOU7v2NFDmcsBmSFDt5EHOgp/jeTF3O/q'))
    assert.ok(bcrypt.compareSync('RYoj\\_>2P7', '$2a$12$esIAHiQAJNNBrsr5V13l7.RFWWJI2BZFtQlkFyiWXjou05GyuREZa'))
    assert.ok(bcrypt.compareSync('^Q&"]A`%/A(BVGt>QaX0M-#<Q148&f', '$2a$04$vrRP5vQxyD4LrqiLd/oWROgrrGINsw3gb4Ga5x2sn01jNmiLVECl6'))
    assert.ok(bcrypt.compareSync('nZa!rRf\\U;OL;R?>1ghq_+":Y0CRmY', '$2a$05$YuQvhokOGVnevctykUYpKutZD2pWeGGYn3auyLOasguMY3/0BbIyq'))
    assert.ok(bcrypt.compareSync("F%uN/j>[GuB7-jB'_Yj!Tnb7Y!u^6)", '$2a$06$5L3vpQ0tG9O7k5gQ8nAHAe9xxQiOcOLh8LGcI0PLWhIznsDt.S.C6'))
    assert.ok(bcrypt.compareSync('Z>BobP32ub"Cfe*Q<<WUq3rc=[GJr-', '$2a$07$hp8IdLueqE6qFh1zYycUZ.twmUH8eSTPQAEpdNXKMlwms9XfKqfea'))
    assert.ok(bcrypt.compareSync("Ik&8N['7*[1aCc1lOm8\\jWeD*H$eZM", '$2a$08$2ANDTYCB9m7vf0Prh7rSrupqpO3jJOkIz2oW/QHB4lCmK7qMytGV6'))
    assert.ok(bcrypt.compareSync('O)=%3[E$*q+>-q-=tRSjOBh8\\mLNW.', '$2a$09$nArqOfdCsD9kIbVnAixnwe6s8QvyPYWtQBpEXKir2OJF9/oNBsEFe'))
    assert.ok(bcrypt.compareSync('/MH51`!BP&0tj3%YCA;Xk%e3S`o\\EI', '$2a$10$ePiAc.s.yoBi3B6p1iQUCezn3mraLwpVJ5XGelVyYFKyp5FZn/y.u'))
    assert.ok(bcrypt.compareSync('ptAP"mcg6oH.";c0U2_oll.OKi<!ku', '$2a$12$aroG/pwwPj1tU5fl9a9pkO4rydAmkXRj/LqfHZOSnR6LGAZ.z.jwa'))
    assert.ok(bcrypt.compareSync('Q/A:k3DP;X@=<0"hg&9c', '$2a$04$wbgDTvLMtyjQlNK7fjqwyOakBoACQuYh11.VsKNarF4xUIOBWgD6S'))
    assert.ok(bcrypt.compareSync('Q/A:k3DP;X@=<0"hg&9c', '$2a$05$zbAaOmloOhxiKItjznRqrunRqHlu3MAa7pMGv26Rr3WwyfGcwoRm6'))
    assert.ok(bcrypt.compareSync('Q/A:k3DP;X@=<0"hg&9c', '$2a$06$aOK0bWUvLI0qLkc3ti5jyuAIQoqRzuqoK09kQqQ6Ou/YKDhW50/qa'))
    assert.ok(bcrypt.compareSync("o<&+X'F4AQ8H,LU,N`&r", '$2a$04$BK5u.QHk1Driey7bvnFTH.3smGwxd91PtoK2GxH5nZ7pcBsYX4lMq'))
    assert.ok(bcrypt.compareSync("o<&+X'F4AQ8H,LU,N`&r", '$2a$05$BK5u.QHk1Driey7bvnFTH.t5P.jZvFBMzDB1IY4PwkkRPOyVbEtFG'))
    assert.ok(bcrypt.compareSync("o<&+X'F4AQ8H,LU,N`&r", '$2a$06$BK5u.QHk1Driey7bvnFTH.6Ea1Z5db2p25CPXZbxb/3OyKQagg3pa'))
    assert.ok(bcrypt.compareSync("o<&+X'F4AQ8H,LU,N`&r", '$2a$07$BK5u.QHk1Driey7bvnFTH.sruuQi8Lhv/0LWKDvNp3AGFk7ltdkm6'))
    assert.ok(bcrypt.compareSync("o<&+X'F4AQ8H,LU,N`&r", '$2a$08$BK5u.QHk1Driey7bvnFTH.IE7KsaUzc4m7gzAMlyUPUeiYyACWe0q'))
    assert.ok(bcrypt.compareSync("o<&+X'F4AQ8H,LU,N`&r", '$2a$09$BK5u.QHk1Driey7bvnFTH.1v4Xj1dwkp44QNg0cVAoQt4FQMMrvnS'))
    assert.ok(bcrypt.compareSync("o<&+X'F4AQ8H,LU,N`&r", '$2a$10$BK5u.QHk1Driey7bvnFTH.ESINe9YntUMcVgFDfkC.Vbhc9vMhNX2'))
    assert.ok(bcrypt.compareSync("o<&+X'F4AQ8H,LU,N`&r", '$2a$12$BK5u.QHk1Driey7bvnFTH.QM1/nnGe/f5cTzb6XTTi/vMzcAnycqG'))
    assert.ok(bcrypt.compareSync('g*3Q45="8NNgpT&mbMJ$Omfr.#ZeW?FP=CE$#roHd?97uL0F-]`?u73c"\\[."*)qU34@VG', '$2a$04$T2XJ5MOWvHQZRijl8LIKkOQKIyX75KBfuLsuRYOJz5OjwBNF2lM8a'))
    assert.ok(bcrypt.compareSync('\\M+*8;&QE=Ll[>5?Ui"^ai#iQH7ZFtNMfs3AROnIncE9"BNNoEgO[[*Yk8;RQ(#S,;I+aT', '$2a$05$wgkOlGNXIVE2fWkT3gyRoOqWi4gbi1Wv2Q2Jx3xVs3apl1w.Wtj8C'))
    assert.ok(bcrypt.compareSync("M.E1=dt<.L0Q&p;94NfGm_Oo23+Kpl@M5?WIAL.[@/:'S)W96G8N^AWb7_smmC]>7#fGoB", '$2a$06$W9zTCl35nEvUukhhFzkKMekjT9/pj7M0lihRVEZrX3m8/SBNZRX7i'))
    assert.ok(bcrypt.compareSync('a', '$2a$04$5DCebwootqWMCp59ISrMJ.l4WvgHIVg17ZawDIrDM2IjlE64GDNQS'))
    assert.ok(bcrypt.compareSync('aa', '$2a$04$5DCebwootqWMCp59ISrMJ.AyUxBk.ThHlsLvRTH7IqcG7yVHJ3SXq'))
    assert.ok(bcrypt.compareSync('aaa', '$2a$04$5DCebwootqWMCp59ISrMJ.BxOVac5xPB6XFdRc/ZrzM9FgZkqmvbW'))
    assert.ok(bcrypt.compareSync('aaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.Qbr209bpCtfl5hN7UQlG/L4xiD3AKau'))
    assert.ok(bcrypt.compareSync('aaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.oWszihPjDZI0ypReKsaDOW1jBl7oOii'))
    assert.ok(bcrypt.compareSync('aaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ./k.Xxn9YiqtV/sxh3EHbnOHd0Qsq27K'))
    assert.ok(bcrypt.compareSync('aaaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.PYJqRFQbgRbIjMd5VNKmdKS4sBVOyDe'))
    assert.ok(bcrypt.compareSync('aaaaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ..VMYfzaw1wP/SGxowpLeGf13fxCCt.q'))
    assert.ok(bcrypt.compareSync('aaaaaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.5B0p054nO5WgAD1n04XslDY/bqY9RJi'))
    assert.ok(bcrypt.compareSync('aaaaaaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.INBTgqm7sdlBJDg.J5mLMSRK25ri04y'))
    assert.ok(bcrypt.compareSync('aaaaaaaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.s3y7CdFD0OR5p6rsZw/eZ.Dla40KLfm'))
    assert.ok(bcrypt.compareSync('aaaaaaaaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.Jx742Djra6Q7PqJWnTAS.85c28g.Siq'))
    assert.ok(bcrypt.compareSync('aaaaaaaaaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.oKMXW3EZcPHcUV0ib5vDBnh9HojXnLu'))
    assert.ok(bcrypt.compareSync('aaaaaaaaaaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.w6nIjWpDPNSH5pZUvLjC1q25ONEQpeS'))
    assert.ok(bcrypt.compareSync('aaaaaaaaaaaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.k1b2/r9A/hxdwKEKurg6OCn4MwMdiGq'))
    assert.ok(bcrypt.compareSync('aaaaaaaaaaaaaaaa', '$2a$04$5DCebwootqWMCp59ISrMJ.3prCNHVX1Ws.7Hm2bJxFUnQOX9f7DFa'))
    assert.ok(bcrypt.compareSync('àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝðÐ', '$2a$04$D3qS2aoTVyqM7z8v8crLm.3nKt4CzBZJbyFB.ZebmfCvRw7BGs.Xm'))
    assert.ok(bcrypt.compareSync('àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝðÐ', '$2a$05$VA1FujiOCMPkUHQ8kF7IaOg7NGaNvpxwWzSluQutxEVmbZItRTsAa'))
    assert.ok(bcrypt.compareSync('àèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝðÐ', '$2a$06$TXiaNrPeBSz5ugiQlehRt.gwpeDQnXWteQL4z2FulouBr6G7D9KUi'))
    assert.ok(bcrypt.compareSync('âêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿ', '$2a$04$YTn1Qlvps8e1odqMn6G5x.85pqKql6w773EZJAExk7/BatYAI4tyO'))
    assert.ok(bcrypt.compareSync('âêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿ', '$2a$05$C.8k5vJKD2NtfrRI9o17DOfIW0XnwItA529vJnh2jzYTb1QdoY0py'))
    assert.ok(bcrypt.compareSync('âêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿ', '$2a$06$xqfRPj3RYAgwurrhcA6uROtGlXDp/U6/gkoDYHwlubtcVcNft5.vW'))
    assert.ok(bcrypt.compareSync('ÄËÏÖÜŸåÅæÆœŒßçÇøØ¢¿¡€', '$2a$04$y8vGgMmr9EdyxP9rmMKjH.wv2y3r7yRD79gykQtmb3N3zrwjKsyay'))
    assert.ok(bcrypt.compareSync('ÄËÏÖÜŸåÅæÆœŒßçÇøØ¢¿¡€', '$2a$05$iYH4XIKAOOm/xPQs7xKP1upD0cWyMn3Jf0ZWiizXbEkVpS41K1dcO'))
    assert.ok(bcrypt.compareSync('ÄËÏÖÜŸåÅæÆœŒßçÇøØ¢¿¡€', '$2a$06$wCOob.D0VV8twafNDB2apegiGD5nqF6Y1e6K95q6Y.R8C4QGd265q'))
    assert.ok(bcrypt.compareSync('ΔημοσιεύθηκεστηνΕφημερίδατης', '$2a$04$E5SQtS6P4568MDXW7cyUp.18wfDisKZBxifnPZjAI1d/KTYMfHPYO'))
    assert.ok(bcrypt.compareSync('АБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмН', '$2a$04$03e26gQFHhQwRNf81/ww9.p1UbrNwxpzWjLuT.zpTLH4t/w5WhAhC'))
    assert.ok(bcrypt.compareSync('нОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮю', '$2a$04$PHNoJwpXCfe32nUtLv2UpuhJXOzd4k7IdFwnEpYwfJVCZ/f/.8Pje'))
    assert.ok(bcrypt.compareSync('電电電島岛島兔兔兎龜龟亀國国国區区区', '$2a$04$wU4/0i1TmNl2u.1jIwBX.uZUaOL3Rc5ID7nlQRloQh6q5wwhV/zLW'))
    assert.ok(bcrypt.compareSync('诶比伊艾弗豆贝尔维吾艾尺开艾丝维贼德', '$2a$04$P4kreGLhCd26d4WIy7DJXusPkhxLvBouzV6OXkL5EB0jux0osjsry'))
    assert.ok(bcrypt.compareSync('-O_=*N!2JP', '$2a$04$......................JjuKLOX9OOwo5PceZZXSkaLDvdmgb82'))
    assert.ok(bcrypt.compareSync('7B[$Q<4b>U', '$2a$05$......................DRiedDQZRL3xq5A5FL8y7/6NM8a2Y5W'))
    assert.ok(bcrypt.compareSync('>d5-I_8^.h', '$2a$06$......................5Mq1Ng8jgDY.uHNU4h5p/x6BedzNH2W'))
    assert.ok(bcrypt.compareSync(')V`/UM/]1t', '$2a$04$.OC/.OC/.OC/.OC/.OC/.OQIvKRDAam.Hm5/IaV/.hc7P8gwwIbmi'))
    assert.ok(bcrypt.compareSync(':@t2.bWuH]', '$2a$05$.OC/.OC/.OC/.OC/.OC/.ONDbUvdOchUiKmQORX6BlkPofa/QxW9e'))
    assert.ok(bcrypt.compareSync('b(#KljF5s"', '$2a$06$.OC/.OC/.OC/.OC/.OC/.OHfTd9e7svOu34vi1PCvOcAEq07ST7.K'))
    assert.ok(bcrypt.compareSync('@3YaJ^Xs]*', '$2a$04$eGA.eGA.eGA.eGA.eGA.e.stcmvh.R70m.0jbfSFVxlONdj1iws0C'))
    assert.ok(bcrypt.compareSync("'\"5\\!k*C(p", '$2a$05$eGA.eGA.eGA.eGA.eGA.e.vR37mVSbfdHwu.F0sNMvgn8oruQRghy'))
    assert.ok(bcrypt.compareSync("edEu7C?$'W", '$2a$06$eGA.eGA.eGA.eGA.eGA.e.tSq0FN8MWHQXJXNFnHTPQKtA.n2a..G'))
    assert.ok(bcrypt.compareSync('N7dHmg\\PI^', '$2a$04$999999999999999999999uCZfA/pLrlyngNDMq89r1uUk.bQ9icOu'))
    assert.ok(bcrypt.compareSync('"eJuHh!)7*', '$2a$05$999999999999999999999uj8Pfx.ufrJFAoWFLjapYBS5vVEQQ/hK'))
    assert.ok(bcrypt.compareSync('ZeDRJ:_tu:', '$2a$06$999999999999999999999u6RB0P9UmbdbQgjoQFEJsrvrKe.BoU6q'))
  })
})
